---
title: "Initial Study Baseline"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
```

```{r Loading Packages, message = F, warning = F}
# Loading libraries
packages <- c(
  "dplyr", "ggplot2", "tidyverse",
  "repr", "ggsci", "ggrepel", 
  "lubridate", "forcats", "ggpubr",
  "lemon"
)
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

lapply(packages, require, character.only = TRUE)
```


```{r Denominator counts}
# Putting denominator counts in dataframe

denom_counts <- data.frame(rbind(
  c("Black or African American", "GA", "Male", 426619),
  c("Black or African American", "GA", "Female", 624548),
  c("White", "GA", "Male", 405619),
  c("White", "GA", "Female", 535392),
  c("Other Race", "GA", "Male", 209061),
  c("Other Race", "GA", "Female", 219146),
  c("Asian", "GA", "Male", 21416),
  c("Asian", "GA", "Female", 25407),
  c("American Indian or Alaska Native", "GA", "Male", 1113),
  c("American Indian or Alaska Native", "GA", "Female", 1868)
))
names(denom_counts) <- c("race_concept_id", "state", "gender_concept_id", "count")

denom_counts <- denom_counts %>%
  mutate(
    race_concept_id = as.factor(race_concept_id),
    state = as.factor(state),
    gender_concept_id = as.factor(gender_concept_id),
    count = as.numeric(count))

```


```{r Reading data dictionary}
# Reading the data dictionary
baseName <- "/Users/mhy3/Box/CHAI_UPLOAD_BOX/04212022-study_initial_baseline/"
data <- read.csv(paste0(baseName, "data_dictionary.csv"))
head(data)

```

```{r Reading files and getting counts}
# This function will take in 2 parameters:
# dataDictionary--master list with all the csv files
# condition--Bipolar Disorder, Depression, Suicidality
# @examples
# \dontrun{
# getCounts(data, "Bipolar Disorder")
# }

getCounts <- function(dataDictionary, conditionName) {
  ids <- dataDictionary %>% filter(condition == !!conditionName)
  cohort <- data.frame()
  for (i in ids$id) {
    df <- read.csv(paste0(baseName, i, ".csv"))
    if (dim(df)[2] == 5) {
      cohort <- rbind(cohort, df)
    } else {
      # print(i)
      next
    }
  }
  cohort <- cohort %>%
    mutate(
      race_concept_id = as.factor(race_concept_id),
      state = as.factor(state),
      age_group = as.factor(age_group),
      gender_concept_id = as.factor(gender_concept_id),
      condition = as.factor(conditionName)
    ) %>%
    arrange(age_group) %>%
    distinct() %>% 
    mutate(race_concept_id = recode(race_concept_id, 
                                    "8527" = "White", 
                                    "8516" = "Black or African American", 
                                    "8515" = "Asian", 
                                    "8522" = "Other Race", 
                                    "8657" = "American Indian or Alaska Native"),
           gender_concept_id = recode(gender_concept_id, 
                                      "8507" = "Male", 
                                      "8532" = "Female"))
  return(cohort)
}

# Getting condition dataframes 
bipolar <- getCounts(data, "Bipolar Disorder")
depression <- getCounts(data, "Depression")
suicidality <- getCounts(data, "Suicidality")

# Creating a combined dataframe 
rbind(bipolar, depression, suicidality) %>%
  mutate(race_concept_id = fct_reorder(race_concept_id,
                                       count, .fun = sum, 
                                       .desc = TRUE)) -> all_data

# outdated, not in use: 
# gettingCounts <- function(dataDictionary, condition, race, gender){
#    cohort <- data.frame()
#    ids <- dataDictionary %>% filter(condition == !!condition,
#                                    race == !!race,
#                                    gender == !!gender)
#    for(i in ids$id){
#       df <- read.csv(paste0(baseName, i, ".csv"))
#       if(dim(df)[2] == 5){
#          cohort <- rbind(cohort, df)
#       } else{
#          next
#       }
#    }
#    cohort <- cohort %>% arrange(age_group) %>% distinct()
#    return(cohort)
# }

```

```{r Themes for Graphing}
theme_pie <- function(){
  theme_pubr() + 
  theme(panel.grid = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        legend.title = element_blank()
        )
}

theme_bar <- function(){
  theme_pubr() + 
  theme(plot.title = element_text(vjust = 1),
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(angle = 90, vjust = 1),
        legend.title = element_blank())
}
```



```{r Heatmaps}
# Heat map for bipolar disorder by age and race
bipolar %>% 
  group_by(race_concept_id, age_group) %>% 
  summarise(count = sum(count)) %>% 
  ungroup() %>% 
  mutate(value = count/sum(count),
         race_concept_id = fct_reorder(race_concept_id, value)) %>% 
  ggplot(aes(x = age_group, y = str_wrap(race_concept_id, width = 15)))+
  geom_tile(aes(fill = value)) + 
  theme(axis.title = element_blank()) + 
  labs(title = "Heatmap of Race and Age Groups", 
       subtitle = "Bipolar Disorder") -> heat_bipolar

# Heat map for depression by age and race
depression %>% 
  group_by(race_concept_id, age_group) %>% 
  summarise(count = sum(count)) %>% 
  ungroup() %>% 
  mutate(value = count/sum(count),
         race_concept_id = fct_reorder(race_concept_id, value)) %>% 
  ggplot(aes(x = age_group, y = str_wrap(race_concept_id, width = 15)))+
  geom_tile(aes(fill = value)) + 
  theme(axis.title = element_blank()) + 
  labs(title = "Heatmap of Race and Age Groups", 
       subtitle = "Depression") -> heat_depression

# Heat map for suicidality by age and race
suicidality %>% 
  group_by(race_concept_id, age_group) %>% 
  summarise(count = sum(count)) %>% 
  ungroup() %>% 
  mutate(value = count/sum(count),
         race_concept_id = fct_reorder(race_concept_id, value)) %>% 
  ggplot(aes(x = age_group, y = str_wrap(race_concept_id, width = 15)))+
  geom_tile(aes(fill = value)) + 
  theme(axis.title = element_blank()) + 
  labs(title = "Heatmap of Race and Age Groups", 
       subtitle = "Suicidality") -> heat_suicidality
```



```{r Depression Graphs}
# Depression counts by age group raw counts
depression %>% 
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
  group_by(age_group) %>% 
  summarise(count = sum(count)) %>% 
  mutate(freq = round(count/sum(count)*100, 2),
         cs = rev(cumsum(rev(freq))),
         pos = freq/2 + lead(cs,1),
         pos = if_else(is.na(pos), freq/2, pos), 
         top5 = rank(-count) %in% 1:5) %>% 
  ggplot(aes(x = age_group, y = count)) + 
  geom_line(size = 1.2, aes(group=1), color = "#0072B5FF",
            key_glyph = "rect") +
  geom_point(size = 1.6)+
  geom_bar(stat = "identity",
           position = position_dodge2(width = 0.7, preserve = "single"), 
           fill = "#0072B5FF",
           alpha= 0.3,
           show.legend = FALSE)+
  geom_text(aes(label = paste0(freq, "%")), position = position_stack(vjust = 0.5))+
  theme_pubr()+
  theme(legend.title = element_blank(),
        plot.margin = unit(c(1.5,.5,.5,.5), "cm"),
        plot.title = element_text(vjust = 3),
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(angle =90, vjust = 2)) + 
  labs(x = "Age Group", y = "Count", 
       title = "Depression across Age Groups") -> dep_age

# Interaction plot of age and races raw counts
depression %>%
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
  group_by(age_group, race_concept_id) %>% 
  summarise(count = sum(count)) %>% 
  ggplot(aes(x = age_group, y = count)) + 
  geom_line(size = 1.2, aes(group = race_concept_id, color = race_concept_id),
            key_glyph = "rect") + 
  geom_point(size = 1.6, aes(color = race_concept_id))+
  # geom_text(size = 4, aes(x = "Female", 
  #                         label = if_else(gender_concept_id == "Female", 
  #                                         str_wrap(race_concept_id,20), NULL), 
  #                         color = race_concept_id), nudge_x = 0.04, hjust = 0) +
  scale_color_nejm(labels = function(x) str_wrap(x, width = 20))+
  theme_pubr()+
  theme(panel.grid.major = element_line(color = "#DAE1E7"),
        panel.grid.major.x = element_blank(),
        legend.title = element_blank()) + 
  labs(x = "", y = "Count", 
       title = "Interaction between Age and Race for Depression")


# Double bar graph of counts by age and gender
depression %>% 
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE),
         gender_concept_id = fct_rev(gender_concept_id)) %>% 
  group_by(age_group, gender_concept_id) %>% 
  summarise(count = sum(count)) %>% 
  ggplot(aes(x = age_group, y = count)) + 
  geom_line(size = 1.2, aes(group=gender_concept_id, color = gender_concept_id),
            key_glyph = "rect") +
  geom_point(size = 1.6, aes(group=gender_concept_id, color = gender_concept_id), 
             show.legend = FALSE)+
  geom_bar(aes(fill = gender_concept_id), stat = "identity",
           position = position_dodge2(width = 0.7, preserve = "single"), 
           alpha= 0.3)+
  theme_pubr()+
  scale_color_nejm()+
  scale_fill_nejm()+
  theme(legend.title = element_blank(),
        plot.margin = unit(c(1.5,.5,.5,.5), "cm"),
        plot.title = element_text(vjust = 3),
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(angle =90, vjust = 2)) + 
  labs(x = "Age Group", y = "Count", 
       title = "Depression across Age and Gender")
```



```{r Interaction Plots for all the conditions}
rbind(bipolar, depression, suicidality) %>%
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
  group_by(race_concept_id, gender_concept_id, condition) %>% 
  summarise(sum = sum(count)) %>% 
  ggplot(aes(x = gender_concept_id, y = sum)) + 
  geom_line(size = 1.2, aes(group = race_concept_id, color = race_concept_id),
            key_glyph = "rect") + 
  geom_point(size = 1.6, aes(color = race_concept_id))+
  # geom_text(size = 4, aes(x = "Female", 
  #                         label = if_else(gender_concept_id == "Female", 
  #                                         str_wrap(race_concept_id,20), NULL), 
  #                         color = race_concept_id), nudge_x = 0.04, hjust = 0) +
  scale_color_nejm(labels = function(x) str_wrap(x, width = 20))+
  theme_pubr()+
  theme(panel.grid.major = element_line(color = "#DAE1E7"),
        panel.grid.major.x = element_blank(),
        legend.title = element_blank()) + 
  labs(x = "", y = "Count", 
       title = "Interaction between Gender and Race")+
  facet_wrap(~condition, scales = "free") -> gender_race


rbind(bipolar, depression, suicidality) %>%
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
  group_by(age_group, condition) %>% 
  summarise(sum = sum(count)) %>% 
  ggplot(aes(x = age_group, y = sum)) + 
  geom_line(size = 1.2, aes(group = condition, color = condition),
            key_glyph = "rect") + 
  geom_point(size = 1.6, aes(color = condition))+
  geom_bar(aes(fill = condition), stat = "identity",
           position = position_dodge2(width = 0.8, preserve = "single"), 
           alpha= 0.3,
           show.legend = FALSE) +
  scale_color_nejm(labels = function(x) str_wrap(x, width = 20))+
  scale_fill_nejm() + 
  scale_y_continuous(n.breaks = 4)+
  theme_pubr()+
  theme(legend.title = element_blank()) + 
  labs(x = "Age Group", y = "Count",
       title = "Interaction between Age and Condition")+
  facet_wrap(~condition, scales = "free_y", nrow = 3) -> age_condition


```

```{r Bipolar Disorder for White/Black Pie chart}
bipolar %>% 
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
  group_by(race_concept_id) %>% summarize(count = sum(count)) %>% 
  mutate(freq = round(count/sum(count)*100, 2),
         cs = rev(cumsum(rev(freq))),
         pos = freq/2 + lead(cs,1),
         pos = if_else(is.na(pos), freq/2, pos), 
         top5 = rank(-count) %in% 1:5) %>% 
  ggplot(aes(x = "", y = freq, fill = race_concept_id))+
  geom_bar(stat = "identity", width = 1, color = "white") + 
  theme_pubr()+
  coord_polar("y", start = 0)+
  labs(fill = "", 
       title = str_wrap("Overall Distribution of Bipolar Disorder by Race",30))+ 
  theme_pie()+
  theme(plot.title = element_text(size = 12),
        legend.position = "bottom")+ 
  geom_text(aes(y = pos, label = if_else(freq > 10, 
                                         paste0(freq, "%"), 
                                         NULL)))+
  scale_fill_nejm(labels = function(x) str_wrap(x, width = 18)) -> bd_race
```

```{r Bipolar Disorder for White/Black Bar graph}
# Double bar graph of counts by age group for white and black/african americans
bipolar %>% 
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
  filter(race_concept_id == "White"| race_concept_id == "Black or African American") %>%
  group_by(race_concept_id, age_group) %>% 
  summarise(sum = sum(count)) %>% 
  ggplot(aes(x = age_group, y = sum)) + 
  geom_line(size = 1.2, aes(group=race_concept_id, color = race_concept_id),
            key_glyph = "rect") +
  geom_point(size = 1.6, aes(group=race_concept_id, color = race_concept_id), 
             show.legend = FALSE)+
  geom_bar(aes(fill = race_concept_id), stat = "identity",
           position = position_dodge2(width = 0.7, preserve = "single"), 
           alpha= 0.3)+
  theme_pubr()+
  scale_color_nejm()+
  scale_fill_nejm() + 
  theme_pubr(base_size = 9) + 
  theme(legend.position = "none",
        axis.title.x = element_text(vjust = -2),
        axis.title.y = element_text(vjust = 3),
        plot.margin = unit(c(1,0,.5,0), "cm"),
        plot.title = element_text(size = 12))+
  labs(x = "Age Group", y = "Count", 
       title = str_wrap(
         "Age Differences in White vs Black or African American populations",40)) -> bd_bw


# double bar graph by age and gender -- too much going on
# bipolar %>% 
#   mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
#   filter(race_concept_id == "White"| race_concept_id == "Black or African American") %>% 
#   ggplot(aes(x = age_group, y = count)) + 
#   geom_bar(aes(fill = race_concept_id), stat = "identity",
#            width = 0.7, position = "dodge") +
#   scale_fill_nejm(labels = function(x) str_wrap(x, width = 20)) + 
#   theme_pubr(base_size = 10) + 
#   theme(plot.title = element_text(vjust = 1),
#         axis.title.x = element_text(vjust = -1),
#         axis.title.y = element_text(angle = 90, vjust = 1),
#         legend.position = "bottom") +
#   labs(fill = "", 
#        title = "Age Differences in White vs Black or African American populations",
#        x = "Age Group", y = "Count") + 
#   guides(fill = guide_legend(direction = "horizontal")) +
#   facet_grid(~gender_concept_id) -> bd_bw_mf

```

```{r Bipolar Disorder for White/Black}
fig1 <- ggarrange(bd_race, bd_bw, widths = c(0.3, 0.7), common.legend = T, legend = "bottom")
annotate_figure(fig1, 
                top = text_grob("Comparing Bipolar Disorder Prevalence", 
                                size = 16, face = "bold"),
                fig.lab.face = "bold")
```


```{r Interaction Plot Bipolar Disorder Age and Race}
bipolar %>%
  mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>% 
  group_by(age_group, race_concept_id) %>% 
  summarise(count = sum(count)) %>% 
  ggplot(aes(x = age_group, y = count)) + 
  geom_line(size = 1.2, aes(group = race_concept_id, color = race_concept_id),
            key_glyph = "rect") + 
  geom_point(size = 1.6, aes(color = race_concept_id))+
  # geom_text(size = 4, aes(x = "Female", 
  #                         label = if_else(gender_concept_id == "Female", 
  #                                         str_wrap(race_concept_id,20), NULL), 
  #                         color = race_concept_id), nudge_x = 0.04, hjust = 0) +
  scale_color_nejm(labels = function(x) str_wrap(x, width = 20))+
  theme_pubr()+
  theme(panel.grid.major = element_line(color = "#DAE1E7"),
        panel.grid.major.x = element_blank(),
        legend.title = element_blank()) + 
  labs(x = "", y = "Count", 
       title = "Interaction between Age and Race for Bipolar Disorder")
```


```{r Pie Chart Gender Race}
# This function will create a pie chart for the gender dist. among different races
# Takes a condition dataframe (bipolar, depression, suicidality)
# @examples
# \dontrun{
# pie_gender(denom_counts)
# }

pie_gender <- function(df){
  options(repr.plot.height = 4, repr.plot.width = 4)
  df %>% 
    mutate(race_concept_id = fct_reorder(race_concept_id, count, .fun = sum, .desc = TRUE)) %>%
    group_by(race_concept_id, gender_concept_id) %>% 
    summarize(count = sum(count)) %>% 
    mutate(freq = round(count/sum(count)*100, 2),
           cs = rev(cumsum(rev(freq))),
           pos = freq/2 + lead(cs,1),
           pos = if_else(is.na(pos), freq/2, pos)) %>% 
    ggplot(aes(x = "", y = freq, fill = gender_concept_id)) +
    geom_bar(stat = "identity", 
             width = 1) + 
    coord_polar("y", start = 0)+
    scale_fill_manual(labels = function(x) str_wrap(x, width = 20), 
                      values = c("#0073C2FF", "#EFC000FF")) + 
    geom_text(aes(y = pos, 
                  label = if_else(freq > 10, 
                                  paste0(freq, "%"), NULL)))+
    theme_pie()+
    facet_wrap(~race_concept_id) -> pie_plot
  return(pie_plot)
}
pie_gender(denom_counts)

```


```{r Prevalence Chart Function}
# Tornado prevalence graph 
prev_df <- function(num_df, raceControlled = FALSE, denom_df = NULL){
  if(raceControlled) {
    df <- inner_join(num_df, denom_df, 
                        by = c("state", "race_concept_id", "gender_concept_id"), 
                        suffix = c(".num", ".denom")) %>% 
    mutate(race_concept_id = fct_reorder(race_concept_id, count.denom, .fun = sum, .desc = TRUE),
           prev = if_else(gender_concept_id == "Female",
                          100*(count.num/count.denom), -100*(count.num/count.denom)))
  } else{
    df <- num_df %>% 
      group_by(race_concept_id, age_group) %>%
      mutate(prev = if_else(gender_concept_id == "Female", 
                            100*count/sum(count), -100*count/sum(count))) 
  } 
  df %>% 
    mutate(race_concept_id = fct_reorder(race_concept_id, prev, .fun = sum, .desc = TRUE)) %>% 
    ggplot(aes(x = age_group, y = prev)) +
    geom_bar(aes(fill = gender_concept_id), stat = "identity",
             width = .9, position = "identity") +
    geom_text(aes(label = if_else(prev > 0, paste0(round(prev,2), "%"), NULL)), 
              stat = "identity", hjust = -0.2, size = 5)+
    geom_text(aes(label = if_else(prev < 0, paste0(round(abs(prev),2), "%"), NULL)), 
              stat = "identity", hjust = 1.1, size = 5)+
    # geom_text(aes(label = if_else(prev > 0, count.num, NULL)), stat = "identity", hjust = -0.2)+
    # geom_text(aes(label = if_else(prev < 0, count.num, NULL)), stat = "identity", hjust = 1.1)+
    geom_label(aes(label = paste0("N = ", count.denom),
                   x = Inf, y = -Inf), size = 5, 
              hjust=0, vjust=1, inherit.aes = FALSE)+
    coord_flip()+
    theme_pubr(base_size = 14) + 
    theme(plot.title = element_text(vjust = 1),
          axis.title.x = element_text(vjust = -1),
          axis.title.y = element_text(angle = 90, vjust = 1),
          legend.title = element_blank(),
          legend.text = element_text(size = 14),
          panel.spacing = unit(1.5, "lines"),
          strip.text = element_text(size = 14), 
          axis.line = element_line())+
    scale_y_continuous(labels = function(x) abs(x), 
                       expand = expansion(mult = 0.5)) +
    scale_fill_manual(values = c("#0073C2FF", "#EFC000FF"))+
    facet_rep_wrap(~race_concept_id, scales = "free_x", 
                   repeat.tick.labels = 'left')+
    labs(x = "Age Group (years)", y = "Prevalence (%)", 
         title = "Bipolar Disorder Crude Prevalence Rates") -> prev_age
  return(prev_age)
}
prev_df(num_df = bipolar, raceControlled = TRUE, denom_df = denom_counts)
```


